export const pageTitles = {
  home: '18Games - Traduções +18',
  jogos: 'Jogos - 18Games',
  login: 'Login - 18Games',
  register: 'Registro - 18Games',
  profile: 'Perfil - 18Games',
  admin: 'Admin - 18Games',
  equipe: 'Nossa Equipe - 18Games',
  apoie: 'Apoie o Projeto - 18Games',
  ferramentas: 'Ferramentas - 18Games',
  regras: 'Regras - 18Games',
  terms: 'Termos de Uso - 18Games',
  privacy: 'Política de Privacidade - 18Games',
  dashboard: 'Dashboard - 18Games',
  'editar-conta': 'Editar Conta - 18Games',
  'forgot-password': 'Recuperar Senha - 18Games',
  'reset-password': 'Redefinir Senha - 18Games',
  'verify-email': 'Verificar Email - 18Games',
  'check-email': 'Verificar Email - 18Games',
  'revert-email': 'Reverter Email - 18Games',
  promote: 'Promoção - 18Games'
};

export const pageDescriptions = {
  home: 'Site de traduções de jogos +18 para português do Brasil',
  jogos: 'Explore nossa biblioteca de traduções de jogos +18 para português do Brasil',
  login: 'Faça login para acessar todas as funcionalidades do 18Games',
  register: 'Crie sua conta no 18Games e acesse nossas traduções',
  profile: 'Gerencie seu perfil e veja suas contribuições',
  admin: 'Painel administrativo do 18Games',
  equipe: 'Conheça nossa equipe de tradutores e colaboradores',
  apoie: 'Apoie o projeto 18Games e ajude-nos a continuar traduzindo',
  ferramentas: 'Ferramentas úteis para tradução de jogos',
  regras: 'Regras e diretrizes da comunidade 18Games',
  terms: 'Termos de uso do site 18Games',
  privacy: 'Nossa política de privacidade',
  dashboard: 'Gerencie suas atividades no 18Games',
  'editar-conta': 'Edite as informações da sua conta',
  'forgot-password': 'Recupere o acesso à sua conta',
  'reset-password': 'Redefina sua senha',
  'verify-email': 'Verifique seu endereço de email',
  'check-email': 'Verifique seu email para continuar',
  'revert-email': 'Reverta a alteração de email',
  promote: 'Conheça os benefícios de ser um membro premium'
};
